name: Extensions  
on: [push]
jobs:
  deploy_source:
    name: Deploy API Using Lambda
    strategy:
      matrix:
        node-version: [12.x]
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and build
        run: |
          npm ci
          npm run build --if-present
        env:
          CI: true

      - name: /extensions get lambda deploy zip
        uses: postman-open-technologies/extensions@main
        with:
            args: zip -qq -r m-s-extensions-g.zip extensions/get/index.js node_modules
      - name: extension get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-extensions-g
            zip_file: m-s-extensions-g.zip
      - name: /extensions post lambda deploy zip
        uses: postman-open-technologies/extensions@main
        with:
            args: zip -qq -r m-s-extensions-po.zip extensions/post/index.js node_modules
      - name: extension get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-extensions-po
            zip_file: m-s-extensions-po.zip
      - name: /extensions/{extension_id} get lambda deploy zip
        uses: postman-open-technologies/extensions@main
        with:
            args: zip -qq -r m-s-extensions-extension-g.zip extensions/extension_id/get/index.js node_modules
      - name: extension get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-extensions-extension-g
            zip_file: m-s-extensions-extension-g.zip
      - name: /extensions/{extension_id} put lambda deploy zip
        uses: postman-open-technologies/extensions@main
        with:
            args: zip -qq -r m-s-extensions-extension-pu.zip extensions/extension_id/put/index.js node_modules
      - name: extension get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-extensions-extension-pu
            zip_file: m-s-extensions-extension-pu.zip
      - name: /extensions/{extension_id} delete lambda deploy zip
        uses: postman-open-technologies/extensions@main
        with:
            args: zip -qq -r m-s-extensions-extension-d.zip extensions/extension_id/delete/index.js node_modules
      - name: extension get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-extensions-extension-d
            zip_file: m-s-extensions-extension-d.zip          
      - name: /extensions/{extension_id}/tags get lambda deploy zip
        uses: postman-open-technologies/extensions@main
        with:
            args: zip -qq -r m-s-extensions-extension-tags-g.zip extensions/extension_id/tags/get/index.js node_modules
      - name: extensions get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-extensions-extension-tags-g
            zip_file: m-s-extensions-extension-tags-g.zip
      - name: /extensions/{extension_id}/tags post lambda deploy zip
        uses: postman-open-technologies/extensions@main
        with:
            args: zip -qq -r m-s-extensions-extension-tags-po.zip extensions/extension_id/tags/post/index.js node_modules
      - name: extensions get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-extensions-extension-tags-po
            zip_file: m-s-extensions-extension-tags-po.zip
      - name: /extensions/{extension_id}/tags/{tag_id} delete lambda deploy zip
        uses: postman-open-technologies/extensions@main
        with:
            args: zip -qq -r m-s-extensions-extension-tags-tag-d.zip extensions/extension_id/tags/tag_id/delete/index.js node_modules
      - name: extensions get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-extensions-extension-tags-tag-d
            zip_file: m-s-extensions-extension-tags-tag-d.zip            